local M = {}

M.categories = {
    {
        key = "WhiteItems",
        option = "items.white",
        items = {
            { id = "AtGMissileMk0" },
            { id = "BountyTag" },
            { id = "CheatDeath" },
            { id = "Concentration" },
            { id = "ElephantGun" },
            { id = "FacetedJade" },
            { id = "FearEyes", dependencies = { "FearEyesDeactivate" } },
            { id = "GearFeather" },
            { id = "GiftPurity" },
            { id = "GlassMagnifier" },
            { id = "GoldBar" },
            { id = "GravityLoop", dependencies = { "GravityLoopDeactivate" } },
            { id = "HeavyLungs" },
            { id = "IceMixture" },
            { id = "MagmaFragment" },
            { id = "MassacreCurse" },
            { id = "Obereg" },
            { id = "PainTax" },
            { id = "Rhinoplasty" },
            { id = "ShieldGenerator" },
            { id = "SporeOBloom" },
            { id = "Tankbuster" },
            { id = "ThinWings" },
            { id = "UnfocusPrisma" },
        },
    },
    {
        key = "GreenItems",
        option = "items.green",
        items = {
            { id = "Accountant" },
            { id = "AssemblyBlueprint" },
            { id = "BloodyRelic" },
            { id = "BombardierSwarm" },
            { id = "BountyContract" },
            { id = "CashbackChip" },
            { id = "CharlatansDie" },
            { id = "ContagionBarb" },
            { id = "CoolGlasses" },
            { id = "DeepcoreGK2" },
            { id = "GoldenSneakers" },
            { id = "Golemshot" },
            { id = "GreenTea" },
            { id = "LaughingFungus" },
            { id = "LootFever" },
            { id = "MagicMissile" },
            { id = "NewtonsMechanism" },
            { id = "RadialAlloy" },
            { id = "ReserveCapacitor" },
            { id = "SeaFossil" },
            { id = "ShadowShield" },
            { id = "StandingRequisition" },
            { id = "Totemetry" },
        },
    },
    {
        key = "RedItems",
        option = "items.red",
        items = {
            { id = "ArmySurplus" },
            { id = "CascadeFailure" },
            { id = "Community" },
            { id = "DeadWater" },
            { id = "Dombra" },
            { id = "EyeDiamond" },
            { id = "LeackedCapacitor" },
            { id = "IngrownIdol" },
            { id = "Maslenitsa" },
            { id = "MosquitoNet" },
            { id = "OrbitalLens" },
            { id = "RavenousVine" },
            { id = "RiftBeacon", dependencies = { "RiftBeaconDeactivate" } },
            { id = "RustMite" },
            { id = "ShineOSun" },
            { id = "VioletFrenzy" },
        },
    },
    {
        key = "Equipments",
        option = "items.equipment",
        items = {
            { id = "Annihilator" },
            { id = "Hunger" },
            { id = "Nightshade" },
            { id = "OneArmyMan" },
            { id = "TacticalVisor" },
        },
    },
}

DeerItemsItemManifest = M

return M
